# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     http.client:
         class: GuzzleHttp\Client
     http.service:
         class: AppBundle\Service\Http
         arguments: ['@http.client']
     github.service:
         class: AppBundle\Service\GitHubDB
         arguments: ['@http.service', '@doctrine.orm.entity_manager', '%github_url%']